/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
	'use strict';
	function supportsProperty(p) {
		var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
			i,
			div = document.createElement('div'),
			ret = p in div.style;
		if (!ret) {
			p = p.charAt(0).toUpperCase() + p.substr(1);
			for (i = 0; i < prefixes.length; i += 1) {
				ret = prefixes[i] + p in div.style;
				if (ret) {
					break;
				}
			}
		}
		return ret;
	}
	var icons;
	if (!supportsProperty('fontFeatureSettings')) {
		icons = {
			'sbu-shield': '&#xe600;',
			'yammer': '&#xe601;',
			'home': '&#xe900;',
			'house': '&#xe900;',
			'home2': '&#xe901;',
			'house2': '&#xe901;',
			'newspaper': '&#xe90b;',
			'news': '&#xe90b;',
			'magazine': '&#xe90c;',
			'newspaper2': '&#xe90c;',
			'pencil': '&#xe90e;',
			'write': '&#xe90e;',
			'pencil6': '&#xe913;',
			'write6': '&#xe913;',
			'music3': '&#xe94c;',
			'song3': '&#xe94c;',
			'play': '&#xe957;',
			'video': '&#xe957;',
			'play2': '&#xe958;',
			'video2': '&#xe958;',
			'presentation': '&#xe95c;',
			'board-play': '&#xe95c;',
			'video-camera': '&#xe962;',
			'video10': '&#xe962;',
			'video-camera2': '&#xe963;',
			'video11': '&#xe963;',
			'video-camera3': '&#xe965;',
			'video13': '&#xe965;',
			'connection': '&#xe97c;',
			'wifi': '&#xe97c;',
			'connection2': '&#xe97d;',
			'wifi2': '&#xe97d;',
			'connection3': '&#xe97e;',
			'wifi3': '&#xe97e;',
			'connection4': '&#xe97f;',
			'wifi4': '&#xe97f;',
			'station': '&#xe981;',
			'radio': '&#xe981;',
			'file-empty': '&#xe99d;',
			'file3': '&#xe99d;',
			'file-empty2': '&#xe99e;',
			'file4': '&#xe99e;',
			'file-download': '&#xe9a5;',
			'file9': '&#xe9a5;',
			'file-download2': '&#xe9a6;',
			'file10': '&#xe9a6;',
			'file-upload': '&#xe9a7;',
			'file11': '&#xe9a7;',
			'file-upload2': '&#xe9a8;',
			'file12': '&#xe9a8;',
			'file-check': '&#xe9a9;',
			'file13': '&#xe9a9;',
			'file-check2': '&#xe9aa;',
			'file14': '&#xe9aa;',
			'file-eye': '&#xe9ab;',
			'file15': '&#xe9ab;',
			'file-eye2': '&#xe9ac;',
			'file16': '&#xe9ac;',
			'file-text2': '&#xe9ad;',
			'file17': '&#xe9ad;',
			'file-text3': '&#xe9ae;',
			'file18': '&#xe9ae;',
			'file-picture': '&#xe9af;',
			'file19': '&#xe9af;',
			'file-picture2': '&#xe9b0;',
			'file20': '&#xe9b0;',
			'file-play': '&#xe9b3;',
			'file23': '&#xe9b3;',
			'file-play2': '&#xe9b4;',
			'file24': '&#xe9b4;',
			'file-xml': '&#xe9bb;',
			'file29': '&#xe9bb;',
			'file-xml2': '&#xe9bc;',
			'file30': '&#xe9bc;',
			'file-presentation': '&#xe9bf;',
			'file33': '&#xe9bf;',
			'file-presentation2': '&#xe9c0;',
			'file34': '&#xe9c0;',
			'file-stats': '&#xe9c1;',
			'file35': '&#xe9c1;',
			'file-stats2': '&#xe9c2;',
			'file36': '&#xe9c2;',
			'folder': '&#xe9d0;',
			'directory': '&#xe9d0;',
			'folder2': '&#xe9db;',
			'directory11': '&#xe9db;',
			'folder-open': '&#xe9dc;',
			'directory12': '&#xe9dc;',
			'folder5': '&#xe9e7;',
			'directory23': '&#xe9e7;',
			'folder-open2': '&#xe9e8;',
			'directory24': '&#xe9e8;',
			'price-tag2': '&#xe9ee;',
			'price-tags': '&#xe9ef;',
			'price-tag3': '&#xe9f0;',
			'price-tags2': '&#xe9f1;',
			'phone2': '&#xea1d;',
			'telephone2': '&#xea1d;',
			'phone-wave': '&#xea1f;',
			'telephone4': '&#xea1f;',
			'address-book': '&#xea2b;',
			'contact': '&#xea2b;',
			'at-sign': '&#xea2f;',
			'email': '&#xea2f;',
			'envelop': '&#xea30;',
			'mail': '&#xea30;',
			'envelop2': '&#xea31;',
			'mail2': '&#xea31;',
			'envelop3': '&#xea32;',
			'mail3': '&#xea32;',
			'envelop4': '&#xea33;',
			'mail4': '&#xea33;',
			'pushpin': '&#xea36;',
			'pin': '&#xea36;',
			'location': '&#xea38;',
			'map-marker': '&#xea38;',
			'compass': '&#xea3f;',
			'direction': '&#xea3f;',
			'compass2': '&#xea40;',
			'direction2': '&#xea40;',
			'compass3': '&#xea41;',
			'direction3': '&#xea41;',
			'map4': '&#xea48;',
			'guide4': '&#xea48;',
			'map5': '&#xea49;',
			'guide5': '&#xea49;',
			'direction7': '&#xea4a;',
			'address': '&#xea4a;',
			'clock': '&#xea4d;',
			'time2': '&#xea4d;',
			'clock2': '&#xea4e;',
			'time3': '&#xea4e;',
			'display': '&#xea70;',
			'screen': '&#xea70;',
			'mobile': '&#xea75;',
			'cell-phone': '&#xea75;',
			'tablet': '&#xea77;',
			'mobile3': '&#xea77;',
			'tv': '&#xea79;',
			'television': '&#xea79;',
			'disk2': '&#xea8c;',
			'disc2': '&#xea8c;',
			'usb-stick': '&#xea8d;',
			'flash-memory': '&#xea8d;',
			'server': '&#xea8f;',
			'drives': '&#xea8f;',
			'database': '&#xea90;',
			'db': '&#xea90;',
			'database2': '&#xea91;',
			'db2': '&#xea91;',
			'bubbles': '&#xeac2;',
			'comments': '&#xeac2;',
			'bubbles2': '&#xeac3;',
			'comments2': '&#xeac3;',
			'bubble2': '&#xeac4;',
			'comment2': '&#xeac4;',
			'bubbles3': '&#xeac5;',
			'comments3': '&#xeac5;',
			'bubbles4': '&#xeac6;',
			'comments4': '&#xeac6;',
			'bubble-notification': '&#xeac7;',
			'bubble3': '&#xeac7;',
			'bubble11': '&#xead1;',
			'comment6': '&#xead1;',
			'bubbles7': '&#xead2;',
			'comments7': '&#xead2;',
			'bubble12': '&#xead3;',
			'comment7': '&#xead3;',
			'bubbles8': '&#xead4;',
			'comments8': '&#xead4;',
			'bubble13': '&#xead5;',
			'comment8': '&#xead5;',
			'bubble-dots3': '&#xead6;',
			'bubble14': '&#xead6;',
			'bubble-lines3': '&#xead7;',
			'bubble15': '&#xead7;',
			'bubble16': '&#xead8;',
			'comment9': '&#xead8;',
			'bubble-dots4': '&#xead9;',
			'bubble17': '&#xead9;',
			'bubble-lines4': '&#xeada;',
			'bubble18': '&#xeada;',
			'bubbles10': '&#xeadc;',
			'comments10': '&#xeadc;',
			'user': '&#xeaf4;',
			'profile2': '&#xeaf4;',
			'users': '&#xeaf5;',
			'group': '&#xeaf5;',
			'user-plus': '&#xeaf6;',
			'user2': '&#xeaf6;',
			'user-minus': '&#xeaf7;',
			'user3': '&#xeaf7;',
			'user-cancel': '&#xeaf8;',
			'user4': '&#xeaf8;',
			'user-block': '&#xeaf9;',
			'user5': '&#xeaf9;',
			'user-lock': '&#xeafa;',
			'user6': '&#xeafa;',
			'user-check': '&#xeafb;',
			'user7': '&#xeafb;',
			'users2': '&#xeafc;',
			'group2': '&#xeafc;',
			'users4': '&#xeb09;',
			'group4': '&#xeb09;',
			'user-tie': '&#xeb0a;',
			'user19': '&#xeb0a;',
			'vcard': '&#xeb0e;',
			'card': '&#xeb0e;',
			'quotes-left': '&#xeb18;',
			'ldquo': '&#xeb18;',
			'quotes-right': '&#xeb19;',
			'rdquo': '&#xeb19;',
			'search': '&#xeb2d;',
			'magnifier': '&#xeb2d;',
			'lock2': '&#xeb4e;',
			'secure2': '&#xeb4e;',
			'wrench': '&#xeb55;',
			'tool': '&#xeb55;',
			'wrench2': '&#xeb56;',
			'tool2': '&#xeb56;',
			'wrench3': '&#xeb57;',
			'tool3': '&#xeb57;',
			'equalizer': '&#xeb58;',
			'sliders': '&#xeb58;',
			'equalizer2': '&#xeb59;',
			'sliders2': '&#xeb59;',
			'cogs': '&#xeb5d;',
			'gears': '&#xeb5d;',
			'cog2': '&#xeb5e;',
			'gear2': '&#xeb5e;',
			'cog3': '&#xeb5f;',
			'gear3': '&#xeb5f;',
			'pulse2': '&#xeb6d;',
			'health2': '&#xeb6d;',
			'bug2': '&#xeb76;',
			'virus2': '&#xeb76;',
			'construction': '&#xeb7a;',
			'maintenance': '&#xeb7a;',
			'traffic-cone': '&#xeb7b;',
			'construction2': '&#xeb7b;',
			'traffic-lights': '&#xeb7c;',
			'lights': '&#xeb7c;',
			'pie-chart': '&#xeb7d;',
			'stats': '&#xeb7d;',
			'paw': '&#xebd5;',
			'animal': '&#xebd5;',
			'atom': '&#xebe8;',
			'science': '&#xebe8;',
			'atom2': '&#xebe9;',
			'science2': '&#xebe9;',
			'magnet': '&#xebea;',
			'attract': '&#xebea;',
			'magnet2': '&#xebeb;',
			'attract2': '&#xebeb;',
			'lamp4': '&#xebf3;',
			'light5': '&#xebf3;',
			'lamp5': '&#xebf4;',
			'light6': '&#xebf4;',
			'lamp6': '&#xebf5;',
			'light7': '&#xebf5;',
			'lamp7': '&#xebf6;',
			'light8': '&#xebf6;',
			'puzzle3': '&#xec1e;',
			'puzzle-piece3': '&#xec1e;',
			'puzzle4': '&#xec1f;',
			'puzzle-piece4': '&#xec1f;',
			'power-cord': '&#xec4a;',
			'plugin': '&#xec4a;',
			'lan': '&#xec64;',
			'network': '&#xec64;',
			'cloud': '&#xec72;',
			'weather': '&#xec72;',
			'cloud-download': '&#xec73;',
			'cloud2': '&#xec73;',
			'cloud-upload': '&#xec74;',
			'cloud3': '&#xec74;',
			'cloud-check': '&#xec75;',
			'cloud4': '&#xec75;',
			'cloud5': '&#xec76;',
			'weather2': '&#xec76;',
			'cloud-download2': '&#xec77;',
			'cloud6': '&#xec77;',
			'cloud-upload2': '&#xec78;',
			'cloud7': '&#xec78;',
			'cloud-check2': '&#xec79;',
			'cloud8': '&#xec79;',
			'link': '&#xec96;',
			'chain': '&#xec96;',
			'link3': '&#xec98;',
			'chain2': '&#xec98;',
			'link7': '&#xec9c;',
			'chain4': '&#xec9c;',
			'flag': '&#xeca1;',
			'report': '&#xeca1;',
			'flag2': '&#xeca2;',
			'report2': '&#xeca2;',
			'warning': '&#xed4c;',
			'sign': '&#xed4c;',
			'warning2': '&#xed4d;',
			'sign2': '&#xed4d;',
			'notification': '&#xed4e;',
			'warning3': '&#xed4e;',
			'notification2': '&#xed4f;',
			'warning4': '&#xed4f;',
			'question': '&#xed50;',
			'help': '&#xed50;',
			'question2': '&#xed51;',
			'help2': '&#xed51;',
			'question3': '&#xed52;',
			'help3': '&#xed52;',
			'question4': '&#xed53;',
			'help4': '&#xed53;',
			'plus-circle': '&#xed5c;',
			'add4': '&#xed5c;',
			'minus-circle': '&#xed5d;',
			'remove': '&#xed5d;',
			'plus-circle2': '&#xed5e;',
			'add5': '&#xed5e;',
			'minus-circle2': '&#xed5f;',
			'remove2': '&#xed5f;',
			'info': '&#xed60;',
			'information': '&#xed60;',
			'info2': '&#xed61;',
			'information2': '&#xed61;',
			'cancel-circle': '&#xed62;',
			'close': '&#xed62;',
			'cancel-circle2': '&#xed63;',
			'close2': '&#xed63;',
			'blocked': '&#xed64;',
			'forbidden': '&#xed64;',
			'arrow-up3': '&#xedb6;',
			'up3': '&#xedb6;',
			'arrow-right3': '&#xedba;',
			'right5': '&#xedba;',
			'arrow-down3': '&#xedbe;',
			'down3': '&#xedbe;',
			'arrow-left3': '&#xedc2;',
			'left6': '&#xedc2;',
			'arrow-up5': '&#xedc4;',
			'up5': '&#xedc4;',
			'arrow-right5': '&#xedc5;',
			'right7': '&#xedc5;',
			'arrow-down5': '&#xedc6;',
			'down5': '&#xedc6;',
			'arrow-left5': '&#xedc7;',
			'left8': '&#xedc7;',
			'arrow-up-left': '&#xedc8;',
			'up-left': '&#xedc8;',
			'arrow-up6': '&#xedc9;',
			'up6': '&#xedc9;',
			'arrow-up-right': '&#xedca;',
			'up-right': '&#xedca;',
			'arrow-right6': '&#xedcb;',
			'right8': '&#xedcb;',
			'arrow-down-right': '&#xedcc;',
			'down-right': '&#xedcc;',
			'arrow-down6': '&#xedcd;',
			'down6': '&#xedcd;',
			'arrow-down-left': '&#xedce;',
			'down-left': '&#xedce;',
			'arrow-left6': '&#xedcf;',
			'left9': '&#xedcf;',
			'arrow-up-left3': '&#xedd8;',
			'up-left3': '&#xedd8;',
			'arrow-up8': '&#xedd9;',
			'up8': '&#xedd9;',
			'arrow-up-right3': '&#xedda;',
			'up-right3': '&#xedda;',
			'arrow-right8': '&#xeddb;',
			'right10': '&#xeddb;',
			'arrow-down-right3': '&#xeddc;',
			'down-right3': '&#xeddc;',
			'arrow-down8': '&#xeddd;',
			'down8': '&#xeddd;',
			'arrow-down-left3': '&#xedde;',
			'down-left3': '&#xedde;',
			'arrow-left8': '&#xeddf;',
			'left11': '&#xeddf;',
			'battery-6': '&#xee51;',
			'battery': '&#xee51;',
			'battery-5': '&#xee52;',
			'battery2': '&#xee52;',
			'battery-4': '&#xee53;',
			'battery3': '&#xee53;',
			'battery-2': '&#xee55;',
			'battery5': '&#xee55;',
			'battery-1': '&#xee56;',
			'battery6': '&#xee56;',
			'battery-0': '&#xee57;',
			'battery7': '&#xee57;',
			'battery-charging': '&#xee58;',
			'battery8': '&#xee58;',
			'embed': '&#xeec9;',
			'code': '&#xeec9;',
			'embed2': '&#xeeca;',
			'code2': '&#xeeca;',
			'google-drive': '&#xeee7;',
			'brand5': '&#xeee7;',
			'facebook': '&#xeee8;',
			'brand6': '&#xeee8;',
			'facebook2': '&#xeee9;',
			'brand7': '&#xeee9;',
			'facebook3': '&#xeeea;',
			'brand8': '&#xeeea;',
			'twitter': '&#xeeed;',
			'brand11': '&#xeeed;',
			'twitter2': '&#xeeee;',
			'brand12': '&#xeeee;',
			'twitter3': '&#xeeef;',
			'brand13': '&#xeeef;',
			'feed2': '&#xeef0;',
			'rss': '&#xeef0;',
			'feed3': '&#xeef1;',
			'rss2': '&#xeef1;',
			'youtube': '&#xeef3;',
			'brand14': '&#xeef3;',
			'youtube2': '&#xeef4;',
			'brand15': '&#xeef4;',
			'youtube3': '&#xeef5;',
			'brand16': '&#xeef5;',
			'dropbox': '&#xef0b;',
			'brand38': '&#xef0b;',
			'onedrive': '&#xef0c;',
			'brand39': '&#xef0c;',
			'blogger': '&#xef15;',
			'brand48': '&#xef15;',
			'blogger2': '&#xef16;',
			'brand49': '&#xef16;',
			'tux': '&#xef1a;',
			'brand53': '&#xef1a;',
			'apple2': '&#xef1b;',
			'brand54': '&#xef1b;',
			'android': '&#xef1d;',
			'brand56': '&#xef1d;',
			'windows': '&#xef1e;',
			'brand57': '&#xef1e;',
			'windows8': '&#xef1f;',
			'brand58': '&#xef1f;',
			'git': '&#xef3e;',
			'chrome': '&#xef41;',
			'browser': '&#xef41;',
			'firefox': '&#xef42;',
			'browser2': '&#xef42;',
			'IE': '&#xef43;',
			'browser3': '&#xef43;',
			'opera': '&#xef44;',
			'browser4': '&#xef44;',
			'safari': '&#xef45;',
			'browser5': '&#xef45;',
			'0': 0
		};
		delete icons['0'];
		window.icomoonLiga = function (els) {
			var classes,
				el,
				i,
				innerHTML,
				key;
			els = els || document.getElementsByTagName('*');
			if (!els.length) {
				els = [els];
			}
			for (i = 0; ; i += 1) {
				el = els[i];
				if (!el) {
					break;
				}
				classes = el.className;
				if (/icon-/.test(classes)) {
					innerHTML = el.innerHTML;
					if (innerHTML && innerHTML.length > 1) {
						for (key in icons) {
							if (icons.hasOwnProperty(key)) {
								innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
							}
						}
						el.innerHTML = innerHTML;
					}
				}
			}
		};
		window.icomoonLiga();
	}
}());