<?php

// Plugin definition
$plugin = array(
  'title' => t('Dumbledore'),
  'category' => t('Front Layouts'),
  'icon' => 'dumbledore.png',
  'theme' => 'dumbledore',
  'css' => 'dumbledore.css',
  'regions' => array(

	'banner' => t('Banner'),
	
    'section-a' => t('Section A'),
	'section-b' => t('Section B'),
    'section-c' => t('Section C'),
	
	'section-d' => t('Section D'),
  'section-e' => t('Section E'),
	'section-f' => t('Section F'),
  ),
);
